version: "3.8"

services:
  melotts:
    build: .
    ports:
      - "8888:8888"
    # Uncomment for GPU support if needed
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # runtime: nvidia

